[package]
authors = ["Ceri Storey <ceri@lshift.net>"]
license = "MIT"
name = "phi-accrual"
repository = "https://github.com/cstorey/phi-accrual-rs"
version = "0.1.0"

[dependencies]
log = "0.3.6"
special = "0.7.0"

[dev-dependencies]
env_logger = "0.3.3"
